# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fbaed22062a6667679df5c881efae40398383209650642dd62528261a56eaef1b44e356d7d0d5153974a2c968f8cc6a2d2809d1f3a32dac72f0e5f2a03b7868c

test:
  secret_key_base: 9a9f26c494853909426393ef947c242498c5e25764705497f5b1dae2c93c59b4675362433d21c298915c61424585cb39d2846eae65f4917288bdf8927bd80e35

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
